apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    rkt.alpha.kubernetes.io/stage1-name-override: coreos.com/rkt/stage1-fly
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:{{ config.k8s_hyperkube_tag }}
    command:
    - /hyperkube
    - proxy
    {% if node.is_k8s_apiserver -%}
    - --master=http://127.0.0.1:{{ config.k8s_apiserver_insecure_port }}
    {% else -%}
    {% set apiserver = cluster.nodes.filter_by(is_k8s_apiserver_lb=True).first() -%}
    {% set apiserver_port = config.k8s_apiserver_lb_port -%}
    {% if not apiserver -%}
    {% set apiserver = cluster.nodes.filter_by(is_k8s_apiserver=True).first() -%}
    {% set apiserver_port = config.k8s_apiserver_secure_port -%}
    {% endif -%}
    - --master=https://{{apiserver_lb}}:{{ apiserver_port }}
    {% endif -%}
    {% if not node.is_k8s_apiserver -%}
    - --kubeconfig=/etc/kubernetes/kubeconfig.yaml
    {% endif -%}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs
      readOnly: true
    - mountPath: /etc/kubernetes/kubeconfig.yaml
      name: kubeconfig
      readOnly: true
    - mountPath: /var/run/dbus
      name: dbus
      readOnly: false
  volumes:
  - name: ssl-certs
    hostPath:
      path: /usr/share/ca-certificates
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes/kubeconfig.yaml
  - name: dbus
    hostPath:
      path: /var/run/dbus
