apiVersion: v1
kind: Config
clusters:
- name: {{ cluster.name }}
  cluster:
    server: {{ cluster.k8s_apiserver_endpoint }}
    certificate-authority: {{ config.ca_cert_path }}
users:
- name: kubelet
  user:
    client-certificate: {{ config.node_cert_path }}
    client-key: {{ config.node_key_path }}
contexts:
- context:
    cluster: {{ cluster.name }}
    user: kubelet
