apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    rkt.alpha.kubernetes.io/stage1-name-override: coreos.com/rkt/stage1-fly
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:{{ hyperkube_tag }}
    command:
    - /hyperkube
    - proxy
    - --master={{ apiserver_endpoint }}
    {% if set_kubeconfig -%}
    - --kubeconfig=/etc/kubernetes/kubeconfig.yaml
    {% endif -%}
    securityContext:
      privileged: true
    volumeMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: ssl-cluster-credentials
      mountPath: {{ config.cluster_credentials_path }}
      readOnly: true
    - name: kubeconfig
      mountPath: /etc/kubernetes/kubeconfig.yaml
      readOnly: true
    - name: dbus
      mountPath: /var/run/dbus
      readOnly: false
  volumes:
  - name: ssl-certs
    hostPath:
      path: /usr/share/ca-certificates
  - name: ssl-cluster-credentials
    hostPath:
      path: {{ config.cluster_credentials_path }}
  - name: kubeconfig
    hostPath:
      path: {{ config.kubeconfig_path }}
  - name: dbus
    hostPath:
      path: /var/run/dbus
