---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: seedbox
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: seedbox
    release: {{ .Release.Name }}
