apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:{{ cluster.k8s_hyperkube_tag }}
    command:
    - /hyperkube
    - proxy
    - --kubeconfig=/etc/kubeconfig.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: {{ config.cluster_credentials_path }}
      name: ssl-certs-cluster
      readOnly: true
    - mountPath: /etc/kubeconfig.yaml
      name: kubeconfig
      readOnly: true
  volumes:
  - hostPath:
      path: {{ config.node_ca_certificates_path }}
    name: ssl-certs-host
  - hostPath:
      path: {{ config.cluster_credentials_path }}
    name: ssl-certs-cluster
  - hostPath:
      path: {{ config.k8s_kubeconfig_path }}
    name: kubeconfig
