apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: {{ config.k8s_hyperkube_image }}:{{ cluster.k8s_hyperkube_tag }}
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:{{ config.k8s_apiserver_insecure_port }}
    - --root-ca-file={{ config.ca_cert_path }}
    - --service-account-private-key-file={{ config.k8s_service_account_private_key_path }}
    - --leader-elect=true
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: {{ config.cluster_credentials_path }}
      name: ssl-certs-cluster
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: {{ config.k8s_secrets_path }}
      name: k8s-secrets
      readOnly: true
  volumes:
  - hostPath:
      path: {{ config.cluster_credentials_path }}
    name: ssl-certs-cluster
  - hostPath:
      path: {{ config.node_ca_certificates_path }}
    name: ssl-certs-host
  - hostPath:
      path: {{ config.k8s_secrets_path }}
    name: k8s-secrets
