apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:{{ cluster.k8s_hyperkube_tag }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --etcd-servers={{ cluster.etcd_endpoints|join(',') }}
    - --allow-privileged=true
    - --service-cluster-ip-range={{ cluster.k8s_service_network }}
    - --secure-port={{ config.k8s_apiserver_secure_port }}
    - --insecure-port={{ config.k8s_apiserver_insecure_port }}
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --tls-cert-file={{ config.node_cert_path }}
    - --tls-private-key-file={{ config.node_key_path }}
    - --client-ca-file={{ config.ca_cert_path }}
    - --service-account-key-file={{ config.node_key_path }}
    - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --anonymous-auth=false
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: {{ config.k8s_apiserver_secure_port }}
      hostPort: {{ config.k8s_apiserver_secure_port }}
      name: https
    - containerPort: {{ config.k8s_apiserver_insecure_port }}
      hostPort: {{ config.k8s_apiserver_insecure_port }}
      name: local
    volumeMounts:
    - mountPath: {{ config.cluster_credentials_path }}
      name: ssl-certs-cluster
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: {{ config.cluster_credentials_path }}
    name: ssl-certs-cluster
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
