apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:{{ cluster.k8s_hyperkube_tag }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    {% if cluster.explicitly_advertise_addresses -%}
    - --advertise-address={{ node.ip }}
    {% endif -%}
    - --secure-port={{ config.k8s_apiserver_secure_port }}
    - --insecure-port={{ config.k8s_apiserver_insecure_port }}
    - --etcd-servers={{ cluster.etcd_endpoints|join(',') }}
    - --etcd-cafile={{ config.ca_cert_path }}
    - --etcd-certfile={{ config.node_cert_path }}
    - --etcd-keyfile={{ config.node_key_path }}
    {% if cluster.etcd_version == 3 -%}
    - --storage-backend=etcd3
    {% endif -%}
    - --allow-privileged=true
    - --service-cluster-ip-range={{ cluster.k8s_service_network }}
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --runtime-config=api/all=true
    - --tls-cert-file={{ config.node_cert_path }}
    - --tls-private-key-file={{ config.node_key_path }}
    - --service-account-key-file={{ config.node_cert_path }}
    - --client-ca-file={{ config.ca_cert_path }}
    - --anonymous-auth=false
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: {{ config.cluster_credentials_path }}
      name: ssl-certs-cluster
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: {{ config.cluster_credentials_path }}
    name: ssl-certs-cluster
  - hostPath:
      path: {{ config.node_ca_certificates_path }}
    name: ssl-certs-host
